### PR TITLE
Change link to rsparkling repo

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR changes the link to rsparkling and points it to rsparkling's new repo location.

### CODE REVIEW

**Comment by jjallaire** [comment]
The links in this file should be changed as well: https://github.com/rstudio/spark.rstudio.com/blob/master/h2o.Rmd

Could you add that to the PR as well as reviewing the h20.Rmd content to ensure it's up to date (it looks to me like it needs some changes to reflect the new repo location).

**Comment by navdeep-G** [comment]
@jjallaire Isn't that the file I changed? Also, I'll review the rest.

**Comment by navdeep-G** [comment]
@jjallaire I've added more updates. I think all are covered.

**Comment by jjallaire** [comment]
Indeed it was! (sorry I thought it was index.Rmd you had change).

**Comment by edgararuiz** [comment]
Hi @navdeep-G , I went ahead and updated the link to the rsparkling GitHub repo in the Extensions page too (http://spark.rstudio.com/extensions.html) .  I add it to a batch of a couple of other updates I just merged, hope that's ok.

**Pull request merged**
